name: Publish Terraform module on Terraform Cloud

on:
  workflow_call:
    inputs:
      ENABLE_CREATE_MODULE_FOLDER:
        required: false
        type: string
        default: false
      WORKING_DIRECTORY:
        required: true
        type: string
      # workding-directory is added to specify terraform module direcotry in project source
      MODULE_NAME:
        required: true
        type: string
      PROVIDER:
        required: false
        type: string
        default: "aws"
    secrets:
      TF_ORGANIZATION:
        description: 'Terraform Organization'
        required: true
      TERRAFORM_REGISTRY_TOKEN:
        description: 'Terraform Registry Token'
        required: true

defaults:
  run:
    shell: bash

jobs:
  publish-tf-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Create Module Folder
        id: create_module
        #if: {{ inputs.ENABLE_CREATE_MODULE_FOLDER == 'true'}}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        uses: wei/curl@v1
        with:
          args: |
            --request POST
            --url "https://app.terraform.io/api/v2/organizations/${{ secrets.TF_ORGANIZATION }}/registry-modules"
            —-header "Content-Type: application/vnd.api+json"
            —-header "Authorization: Bearer ${{ secrets.TERRAFORM_REGISTRY_TOKEN }}"
            —-data '{"type": "registry-modules", "attributes": { "name": ${{ inputs.MODULE_NAME }}, "provider": ${{ inputs.PROVIDER }}, "registry-name": "private" }}'
      