name: s3-lifecycle terratest workflow

on:
  push:
    branches:
      - main
    paths:
      - terraform/modules/s3-lifecycle/**

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform/modules/s3-lifecycle
  unit-test:
    uses: ./.github/workflows/unit-test-workflow.yml
    with:
      working-directory: terraform/modules/s3-lifecycle
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}